name: 🐞 Report a bug
description: Have you found a bug in this repo? Create a bug report!
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        **Please do not report security vulnerabilities here**.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a clear and concise description of the bug, including what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: Detail the steps taken to reproduce this error and whether this issue can be reproduced consistently or if it is intermittent.
      placeholder: |
        1. Step 1...
        2. Step 2...
        3. ...
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: In which version did you find this bug? Other libraries that might be involved, or any other relevant information you think would be useful.
    validations:
      required: false
