name: 🧩 Feature request
description: Suggest an idea or a feature for this repo
labels: ["feature"]

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the feature is.
      placeholder: As a X I would Y so that Z...
    validations:
      required: true
  - type: textarea
    id: acceptance-criterias
    attributes:
      label: Acceptance Criterias
      description: A clear list of which acceptance criterias we got for this feature.
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context, links, references or screenshots about the feature request here.
    validations:
      required: false
